# Generated by Django 5.0.1 on 2024-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_buy_list', '0003_item_bought_date_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
