# Generated by Django 5.0.1 on 2024-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_buy_list', '0005_item_price_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_future',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
